dinner_invites = ['Jesus', 'C.S Lewis', 'Liam']
print(f"Hello {dinner_invites[0]} you are invited to dinner.")
print(f"Hello {dinner_invites[1]} you are invited to dinner.")
print(f"Hello {dinner_invites[2]} you are invited to dinner. \n")
print(f"It semms {dinner_invites[1]} can't make it. It's been recently descoverd that he is dead.")
person = dinner_invites.pop(1)
dinner_invites.insert(2, 'George Washington')
print(f"Hello {dinner_invites[2]} you are invited to dinner.\n")
print("It seems we have a bigger table more people will be added\n")
dinner_invites.insert(0, 'I')
dinner_invites.append('Lightning McQueen')
print(f"Congratulations {person} you are know back on the list")
print(f"{dinner_invites[0]} am invited to my own party")
print(f"{dinner_invites[4]} i'm pretty sure you're not dead, you can come to this totally realistic dinner.")
print(len(dinner_invites))
